# Generated by Django 4.2.6 on 2023-10-11 06:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField()),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('status', models.IntegerField(choices=[(1, 'Completed'), (2, 'Rejected')])),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField()),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='loans_app.loans', to_field='external_id')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='payments_app.payments', to_field='external_id')),
            ],
        ),
    ]
