# Generated by Django 4.2.6 on 2023-10-11 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField()),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('contract_version', models.CharField(max_length=60)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Rejected'), (4, 'Paid')])),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
